import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans, Noto_Serif } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const notoSerif = Noto_Serif({
  variable: "--font-noto-serif",
  subsets: ["latin"],
});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plusJakartaSans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mimos da Poli",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        plusJakartaSans.variable,
        notoSerif.variable,
        "font-inter",
        inter.variable,
      )}
    >
      <body className="bg-background font-inter flex min-h-dvh flex-col">
        {children}
      </body>
    </html>
  );
}
