import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans, Noto_Serif } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  preload: true,
  display: "swap",
});

const notoSerif = Noto_Serif({
  variable: "--font-noto-serif",
  subsets: ["latin"],
  preload: true,
  display: "swap",
});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plusJakartaSans",
  subsets: ["latin"],
  preload: true,
  display: "swap",
});

export const metadata: Metadata = {
  title: "Mimos da Poli",
  description: "Generated by create next app",
  icons: "/logoIcon.png",
  authors: [
    {
      name: "Helcio Anicio",
      url: "https://codandoideias-helcioanicios-projects.vercel.app/",
    },
  ],
  creator: "Codando Ideias",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      className={cn(
        "h-full",
        "antialiased",
        plusJakartaSans.variable,
        notoSerif.variable,
        "font-inter",
        inter.variable,
      )}
    >
      <body
        className="bg-background font-inter flex w-full flex-col overflow-x-hidden"
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
